"use client";
import { createMedRecordForm,deleteMedRecordForm,updateMedRecordForm } from "@/lib/mutations";
import type { Row } from "@/lib/data";
type Field={key:string;label:string;type?:"number"|"date"|"boolean"};
export const medCrudFields:Record<string,Field[]>={
 orders:[{key:"public_code",label:"Номер"},{key:"client_name",label:"Клієнт"},{key:"client_email",label:"Email"},{key:"center",label:"Центр"},{key:"model",label:"Модель"},{key:"status",label:"Статус"},{key:"assigned_to",label:"Відповідальний"}],
 catalog_products:[{key:"slug",label:"Slug"},{key:"name",label:"Назва"},{key:"category",label:"Категорія"},{key:"material",label:"Матеріал"},{key:"compatibility",label:"Сумісність"},{key:"base_price",label:"Ціна",type:"number"},{key:"currency",label:"Валюта"},{key:"status",label:"Статус"},{key:"is_featured",label:"Рекомендований",type:"boolean"},{key:"rating",label:"Рейтинг",type:"number"}],
 crm_clients:[{key:"full_name",label:"Ім’я"},{key:"email",label:"Email"},{key:"phone",label:"Телефон"},{key:"status",label:"Статус"}],
 crm_centers:[{key:"name",label:"Назва"},{key:"city",label:"Місто"},{key:"email",label:"Email"},{key:"phone",label:"Телефон"},{key:"status",label:"Статус"}],
 crm_partners:[{key:"name",label:"Назва"},{key:"kind",label:"Тип"},{key:"email",label:"Email"},{key:"phone",label:"Телефон"},{key:"contract_status",label:"Статус договору"}],
 model_files:[{key:"name",label:"Назва"},{key:"file_type",label:"Формат"},{key:"version",label:"Версія"},{key:"size_bytes",label:"Розмір (байти)",type:"number"},{key:"status",label:"Статус"}],
 deliveries:[{key:"carrier",label:"Перевізник"},{key:"tracking_number",label:"ТТН"},{key:"status",label:"Статус"},{key:"recipient_name",label:"Отримувач"},{key:"destination",label:"Напрямок"}],
 documents:[{key:"title",label:"Назва"},{key:"document_type",label:"Тип"},{key:"status",label:"Статус"},{key:"issued_at",label:"Дата",type:"date"}]
};
function Fields({fields,row}:{fields:Field[];row?:Row}){return <div className="record-fields">{fields.map(field=><label key={field.key}>{field.label}{field.type==="boolean"?<select className="input" name={field.key} defaultValue={String(row?.[field.key]??false)}><option value="false">Ні</option><option value="true">Так</option></select>:<input className="input" name={field.key} type={field.type??"text"} defaultValue={String(row?.[field.key]??"")}/>}</label>)}</div>}
export function MedCrudTable({table,rows}:{table:string;rows:Row[]}){const fields=medCrudFields[table];if(!fields)return null;return <><details className="record-panel"><summary className="btn">+ Додати запис</summary><form action={createMedRecordForm}><input type="hidden" name="table" value={table}/><Fields fields={fields}/><button className="btn">Додати</button></form></details>{!rows.length?<div className="card empty">Даних за цими умовами не знайдено.</div>:<div className="table-wrap"><table><thead><tr>{fields.map(field=><th key={field.key}>{field.label}</th>)}<th>Дії</th></tr></thead><tbody>{rows.map(row=><tr key={String(row.id)}>{fields.map(field=><td key={field.key}>{field.type==="boolean"?(row[field.key]?"Так":"Ні"):String(row[field.key]??"—")}</td>)}<td><details className="record-edit"><summary>Редагувати</summary><form action={updateMedRecordForm}><input type="hidden" name="table" value={table}/><input type="hidden" name="id" value={String(row.id)}/><Fields fields={fields} row={row}/><button className="btn">Зберегти</button></form><form action={deleteMedRecordForm} onSubmit={event=>{if(!window.confirm("Видалити цей запис безповоротно?"))event.preventDefault()}}><input type="hidden" name="table" value={table}/><input type="hidden" name="id" value={String(row.id)}/><button className="btn danger">Видалити</button></form></details></td></tr>)}</tbody></table></div>}</>}
