"use server";import { z } from "zod";import { requirePermission } from "./auth";import { serviceClient } from "./supabase";import { isDemoMode } from "./config";import { recordAndNotify } from "./notifications";import { revalidatePath } from "next/cache";
const orderUpdate=z.object({orderId:z.string().uuid(),status:z.enum(["new","reviewing","quoted","approved","printing","completed","cancelled"]),note:z.string().max(4000)});
export async function updateCalculatorOrder(input:unknown){const actor=await requirePermission("calculator.orders.manage");const parsed=orderUpdate.parse(input);if(isDemoMode())throw new Error("Supabase не підключено");const calc=serviceClient("calculator")!;const {error}=await calc.rpc("admin_update_print_order",{p_order_id:parsed.orderId,p_status:parsed.status,p_admin_note:parsed.note,p_central_actor_id:actor.id,p_actor_email:actor.email});if(error)throw new Error("Статус не змінено: транзакцію відхилено");await recordAndNotify({actorId:actor.id,project:"calculator",action:"calculator.order.status_updated",entityType:"print_order",entityId:parsed.orderId,summary:`${actor.name} змінив(ла) статус заявки на ${parsed.status}`,metadata:{status:parsed.status}});revalidatePath("/calculator/orders");return {ok:true};}
export async function updateCalculatorOrderForm(formData:FormData){await updateCalculatorOrder({orderId:formData.get("orderId"),status:formData.get("status"),note:formData.get("note")})}
const medOrderUpdate=z.object({orderId:z.string().uuid(),status:z.enum(["new","needs_data","modeling","printing","approval","done"])});
export async function updateMedOrderForm(formData:FormData){const actor=await requirePermission("med3druk.orders.manage");const parsed=medOrderUpdate.parse({orderId:formData.get("orderId"),status:formData.get("status")});const med=serviceClient("med3druk");if(!med)throw new Error("MED3DRUK Supabase не підключено");const {error}=await med.from("orders").update({status:parsed.status}).eq("id",parsed.orderId);if(error)throw new Error("Статус MED3DRUK не змінено");await recordAndNotify({actorId:actor.id,project:"med3druk",action:"med3druk.order.status_updated",entityType:"order",entityId:parsed.orderId,summary:`${actor.name} змінив(ла) статус MED3DRUK замовлення на ${parsed.status}`,metadata:{status:parsed.status}});revalidatePath("/med3druk/orders")}

const medResources={orders:{permission:"med3druk.orders.manage",fields:["public_code","client_name","client_email","center","model","status","assigned_to","unit_price"]},catalog_products:{permission:"med3druk.products.manage",fields:["slug","name","category","material","compatibility","base_price","currency","status","is_featured","rating"]},crm_clients:{permission:"med3druk.clients.manage",fields:["full_name","email","phone","status"]},crm_centers:{permission:"med3druk.centers.manage",fields:["name","city","email","phone","status"]},crm_partners:{permission:"med3druk.partners.manage",fields:["name","kind","email","phone","contract_status"]},model_files:{permission:"med3druk.models.manage",fields:["name","file_type","version","size_bytes","status"]},deliveries:{permission:"med3druk.deliveries.manage",fields:["carrier","tracking_number","status","recipient_name","destination"]},documents:{permission:"med3druk.documents.manage",fields:["title","document_type","status","issued_at"]}} as const;
type MedResource=keyof typeof medResources;
function getResource(value:FormDataEntryValue|null){if(typeof value!=="string"||!(value in medResources))throw new Error("Непідтримуваний розділ");const table=value as MedResource;return [table,medResources[table]] as const}
function payload(formData:FormData,fields:readonly string[]){return Object.fromEntries(fields.filter(field=>field!=="unit_price").map(field=>{const raw=formData.get(field);const value=typeof raw==="string"&&raw.trim()!==""?raw.trim():null;if(field==="is_featured")return [field,value==="true"];if(["base_price","rating","size_bytes"].includes(field))return [field,value===null?null:Number(value)];return [field,value]}))}
async function mutateMedRecord(formData:FormData,operation:"created"|"updated"|"deleted"){const [table,resource]=getResource(formData.get("table"));const actor=await requirePermission(resource.permission);if(isDemoMode())throw new Error("Supabase не підключено");const med=serviceClient("med3druk");if(!med)throw new Error("MED3DRUK Supabase не підключено");const id=String(formData.get("id")??"");if(operation!=="created"&&!id)throw new Error("Не вказано запис для зміни");const request=operation==="created"?med.from(table).insert(payload(formData,resource.fields)).select("id").single():operation==="updated"?med.from(table).update(payload(formData,resource.fields)).eq("id",id).select("id").single():med.from(table).delete().eq("id",id).select("id").single();const {data,error}=await request;if(error)throw new Error("Не вдалося зберегти зміни. Перевірте обов’язкові поля.");const entityId=String((data as {id:string}|null)?.id??id);await recordAndNotify({actorId:actor.id,project:"med3druk",action:`med3druk.${table}.${operation}`,entityType:table,entityId,summary:`${actor.name} ${operation==="created"?"додав(ла)":operation==="updated"?"оновив(ла)":"видалив(ла)"} запис у розділі ${table}`});const route:{[key:string]:string}={catalog_products:"products",crm_clients:"clients",crm_centers:"centers",crm_partners:"partners",model_files:"models"};revalidatePath(`/med3druk/${route[table]??table}`)}
export async function createMedRecordForm(formData:FormData){await mutateMedRecord(formData,"created")}
export async function updateMedRecordForm(formData:FormData){await mutateMedRecord(formData,"updated")}
export async function deleteMedRecordForm(formData:FormData){await mutateMedRecord(formData,"deleted")}
export async function saveWorkspaceSettingForm(formData:FormData){const actor=await requirePermission("med3druk.settings.manage"),key=String(formData.get("key")??"").trim(),value=String(formData.get("value")??"").trim();if(!key||!value)throw new Error("Заповніть ключ і значення");let parsed:unknown;try{parsed=JSON.parse(value)}catch{throw new Error("Значення має бути коректним JSON")};const med=serviceClient("med3druk");if(!med)throw new Error("MED3DRUK Supabase не підключено");const {error}=await med.from("workspace_settings").upsert({key,value:parsed,updated_by:actor.id},{onConflict:"key"});if(error)throw new Error("Налаштування не збережено");await recordAndNotify({actorId:actor.id,project:"med3druk",action:"med3druk.settings.saved",entityType:"workspace_setting",entityId:key,summary:`${actor.name} оновив(ла) налаштування ${key}`});revalidatePath("/med3druk/settings")}
export async function deleteWorkspaceSettingForm(formData:FormData){const actor=await requirePermission("med3druk.settings.manage"),key=String(formData.get("key")??"");const med=serviceClient("med3druk");if(!med||!key)throw new Error("Налаштування не знайдено");const {error}=await med.from("workspace_settings").delete().eq("key",key);if(error)throw new Error("Налаштування не видалено");await recordAndNotify({actorId:actor.id,project:"med3druk",action:"med3druk.settings.deleted",entityType:"workspace_setting",entityId:key,summary:`${actor.name} видалив(ла) налаштування ${key}`});revalidatePath("/med3druk/settings")}
