-- Виконати в CENTRAL ADMIN Supabase після 001, якщо 001 вже застосовувалась раніше.
begin;
insert into public.roles(key,name,is_system) values('co_owner','Співвласник',true) on conflict(key) do update set name=excluded.name;
update public.project_memberships m set role_id=(select id from public.roles where key='co_owner') where role_id=(select id from public.roles where key='admin');
delete from public.role_permissions where role_id in(select id from public.roles where key in('co_owner','manager','production','viewer'));
insert into public.role_permissions select r.id,p.id from public.roles r cross join public.permissions p where r.key='co_owner' and p.key not in('roles.manage','calculator.email_verifications.read') on conflict do nothing;
insert into public.role_permissions select r.id,p.id from public.roles r cross join public.permissions p where r.key='manager' and (p.key='projects.read' or ((p.key like 'med3druk.%' or p.key like 'calculator.%') and p.key like '%.read' and p.key<>'calculator.email_verifications.read') or p.key in('med3druk.orders.manage','med3druk.products.manage','med3druk.clients.manage','med3druk.centers.manage','med3druk.partners.manage','med3druk.deliveries.manage','med3druk.documents.manage','calculator.orders.manage','calculator.order_files.download','calculator.uploads.download')) on conflict do nothing;
insert into public.role_permissions select r.id,p.id from public.roles r cross join public.permissions p where r.key='production' and p.key in('projects.read','med3druk.dashboard.read','med3druk.orders.read','med3druk.orders.manage','med3druk.models.read','med3druk.deliveries.read','med3druk.deliveries.manage','calculator.dashboard.read','calculator.orders.read','calculator.orders.manage','calculator.order_files.download') on conflict do nothing;
insert into public.role_permissions select r.id,p.id from public.roles r cross join public.permissions p where r.key='viewer' and (p.key='projects.read' or ((p.key like 'med3druk.%' or p.key like 'calculator.%') and p.key like '%.read' and p.key<>'calculator.email_verifications.read')) on conflict do nothing;
delete from public.roles where key='admin' and not exists(select 1 from public.project_memberships where role_id=roles.id);
commit;
